### PR TITLE
php: do_install cleanup tests dir exists before trying rmdir $TMP

### PR DESCRIPTION
**Pull request by lains**
Build fails at the end of do_install because TMPDIR is inherited from bitbake's TMPDIR (which is an absolute PATH)
The concatenation of D and TMDIR leads to a non existing directory, that we fail to remove.
Testing directory existence on $TMP before issuing rmdir $TMP is a safeguard mesure that will make sure rmdir is only run on actually existing directories.

### CODE REVIEW

**Comment by niziak** [comment]
I can confirm problem which this patch solves.
I'm using Yocto Daisy 1.6.2 with Openembedded from branch Daisy.
My php_5.4.14.bbappend:
EXTRA_OECONF = "--enable-mbstring \
                --enable-fpm \
                --with-zlib=${STAGING_LIBDIR}/.. \
                --with-iconv=${STAGING_LIBDIR}/.. \
                --with-libxml-dir=${STAGING_BINDIR_CROSS} \
                ${COMMON_EXTRA_OECONF} \
               "

I don't know what is exact source of problem, but I got error only on one Ubuntu 14 based machine (on second similar machine everything is OK. Also on Debian 8.0 is OK)

**Comment by niziak** [comment]
I found main difference between systems. Ubuntu 14 bases system where problem occurs had zero size /etc/sshd_config, so environment of logged through SSH user was very reduced.

**Comment by lionelains** [comment]
The patch for this pull request has been transmitted to the openembedded-devel mailing list: 
http://lists.openembedded.org/pipermail/openembedded-devel/2015-February/100480.html

**Comment by lionelains** [comment]
Note: https://github.com/openembedded/meta-oe is obsolescent. This patch should go the new github repo for meta-oe: https://github.com/openembedded/meta-openembedded (in meta-oe subfolder)

**Comment by shr-project** [comment]
Please follow README and submit it to ML for review, thanks.

**Comment by lionelains** [comment]
@shr-project : the code has been submitted to the ML (http://lists.openembedded.org/pipermail/openembedded-devel/2015-February/100480.html). Is that what you meant?

**Comment by shr-project** [comment]
yes, please close this pull-request

**Pull request closed without merging**
